query GetMessages($threadId: Int!) {
  messages(order_by: {created_at: asc}, where: {thread_id: {_eq: $threadId}}) {
    body
    status
    created_at
    created_by
    id
    user {
      id
      image_url
      name
    }
  }
}
