/* eslint-disable */
// @generated by graphql-codegen
// This file was automatically generated and should not be edited.
import * as Types from '../../../../gql/types';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions =  {}
export type GetPostsQueryVariables = Types.Exact<{
  limit: Types.Scalars['Int'];
  status: Types.Scalars['String'];
}>;


export type GetPostsQuery = { __typename?: 'query_root', posts: Array<{ __typename?: 'post', createdAt: any, id: number, slug: string, status: string, title: string, updatedAt: any, userByUpdatedById: { __typename?: 'user', fullName?: string | null | undefined, username?: string | null | undefined }, userByCreatedById: { __typename?: 'user', fullName?: string | null | undefined, username?: string | null | undefined } }> };


export const GetPostsDocument = gql`
    query GetPosts($limit: Int!, $status: String!) {
  posts(
    where: {status: {_eq: $status}}
    limit: $limit
    order_by: {createdAt: desc, title: asc}
  ) {
    createdAt
    id
    slug
    status
    title
    updatedAt
    userByUpdatedById {
      fullName
      username
    }
    userByCreatedById {
      fullName
      username
    }
  }
}
    `;

/**
 * __useGetPostsQuery__
 *
 * To run a query within a React component, call `useGetPostsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetPostsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetPostsQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      status: // value for 'status'
 *   },
 * });
 */
export function useGetPostsQuery(baseOptions: Apollo.QueryHookOptions<GetPostsQuery, GetPostsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetPostsQuery, GetPostsQueryVariables>(GetPostsDocument, options);
      }
export function useGetPostsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetPostsQuery, GetPostsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetPostsQuery, GetPostsQueryVariables>(GetPostsDocument, options);
        }
export type GetPostsQueryHookResult = ReturnType<typeof useGetPostsQuery>;
export type GetPostsLazyQueryHookResult = ReturnType<typeof useGetPostsLazyQuery>;
export type GetPostsQueryResult = Apollo.QueryResult<GetPostsQuery, GetPostsQueryVariables>;