/* eslint-disable */
// @generated by graphql-codegen
// This file was automatically generated and should not be edited.
import {
  FieldPolicy,
  FieldReadFunction,
  TypePolicies,
  TypePolicy,
} from "@apollo/client/cache";
export type messagesKeySpecifier = (
  | "body"
  | "created_at"
  | "created_by"
  | "id"
  | "status"
  | "thread"
  | "thread_id"
  | "updated_at"
  | "user"
  | messagesKeySpecifier
)[];
export type messagesFieldPolicy = {
  body?: FieldPolicy<any> | FieldReadFunction<any>;
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  status?: FieldPolicy<any> | FieldReadFunction<any>;
  thread?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
  user?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_aggregateKeySpecifier = (
  | "aggregate"
  | "nodes"
  | messages_aggregateKeySpecifier
)[];
export type messages_aggregateFieldPolicy = {
  aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  nodes?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_aggregate_fieldsKeySpecifier = (
  | "avg"
  | "count"
  | "max"
  | "min"
  | "stddev"
  | "stddev_pop"
  | "stddev_samp"
  | "sum"
  | "var_pop"
  | "var_samp"
  | "variance"
  | messages_aggregate_fieldsKeySpecifier
)[];
export type messages_aggregate_fieldsFieldPolicy = {
  avg?: FieldPolicy<any> | FieldReadFunction<any>;
  count?: FieldPolicy<any> | FieldReadFunction<any>;
  max?: FieldPolicy<any> | FieldReadFunction<any>;
  min?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  sum?: FieldPolicy<any> | FieldReadFunction<any>;
  var_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  var_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  variance?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_avg_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_avg_fieldsKeySpecifier
)[];
export type messages_avg_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_max_fieldsKeySpecifier = (
  | "body"
  | "created_at"
  | "created_by"
  | "id"
  | "status"
  | "thread_id"
  | "updated_at"
  | messages_max_fieldsKeySpecifier
)[];
export type messages_max_fieldsFieldPolicy = {
  body?: FieldPolicy<any> | FieldReadFunction<any>;
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  status?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_min_fieldsKeySpecifier = (
  | "body"
  | "created_at"
  | "created_by"
  | "id"
  | "status"
  | "thread_id"
  | "updated_at"
  | messages_min_fieldsKeySpecifier
)[];
export type messages_min_fieldsFieldPolicy = {
  body?: FieldPolicy<any> | FieldReadFunction<any>;
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  status?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_mutation_responseKeySpecifier = (
  | "affected_rows"
  | "returning"
  | messages_mutation_responseKeySpecifier
)[];
export type messages_mutation_responseFieldPolicy = {
  affected_rows?: FieldPolicy<any> | FieldReadFunction<any>;
  returning?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_stddev_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_stddev_fieldsKeySpecifier
)[];
export type messages_stddev_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_stddev_pop_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_stddev_pop_fieldsKeySpecifier
)[];
export type messages_stddev_pop_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_stddev_samp_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_stddev_samp_fieldsKeySpecifier
)[];
export type messages_stddev_samp_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_sum_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_sum_fieldsKeySpecifier
)[];
export type messages_sum_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_var_pop_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_var_pop_fieldsKeySpecifier
)[];
export type messages_var_pop_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_var_samp_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_var_samp_fieldsKeySpecifier
)[];
export type messages_var_samp_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type messages_variance_fieldsKeySpecifier = (
  | "created_by"
  | "thread_id"
  | messages_variance_fieldsKeySpecifier
)[];
export type messages_variance_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type mutation_rootKeySpecifier = (
  | "delete_messages"
  | "delete_messages_by_pk"
  | "delete_threads"
  | "delete_threads_by_pk"
  | "delete_threads_users"
  | "delete_threads_users_by_pk"
  | "delete_users"
  | "delete_users_by_pk"
  | "insert_messages"
  | "insert_messages_one"
  | "insert_threads"
  | "insert_threads_one"
  | "insert_threads_users"
  | "insert_threads_users_one"
  | "insert_users"
  | "insert_users_one"
  | "update_messages"
  | "update_messages_by_pk"
  | "update_threads"
  | "update_threads_by_pk"
  | "update_threads_users"
  | "update_threads_users_by_pk"
  | "update_users"
  | "update_users_by_pk"
  | mutation_rootKeySpecifier
)[];
export type mutation_rootFieldPolicy = {
  delete_messages?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_messages_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_threads?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_threads_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_threads_users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_users?: FieldPolicy<any> | FieldReadFunction<any>;
  delete_users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_messages?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_messages_one?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_threads?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_threads_one?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_threads_users_one?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_users?: FieldPolicy<any> | FieldReadFunction<any>;
  insert_users_one?: FieldPolicy<any> | FieldReadFunction<any>;
  update_messages?: FieldPolicy<any> | FieldReadFunction<any>;
  update_messages_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  update_threads?: FieldPolicy<any> | FieldReadFunction<any>;
  update_threads_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  update_threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  update_threads_users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  update_users?: FieldPolicy<any> | FieldReadFunction<any>;
  update_users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type query_rootKeySpecifier = (
  | "messages"
  | "messages_aggregate"
  | "messages_by_pk"
  | "threads"
  | "threads_aggregate"
  | "threads_by_pk"
  | "threads_users"
  | "threads_users_aggregate"
  | "threads_users_by_pk"
  | "users"
  | "users_aggregate"
  | "users_by_pk"
  | query_rootKeySpecifier
)[];
export type query_rootFieldPolicy = {
  messages?: FieldPolicy<any> | FieldReadFunction<any>;
  messages_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  messages_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  threads?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  users?: FieldPolicy<any> | FieldReadFunction<any>;
  users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type subscription_rootKeySpecifier = (
  | "messages"
  | "messages_aggregate"
  | "messages_by_pk"
  | "threads"
  | "threads_aggregate"
  | "threads_by_pk"
  | "threads_users"
  | "threads_users_aggregate"
  | "threads_users_by_pk"
  | "users"
  | "users_aggregate"
  | "users_by_pk"
  | subscription_rootKeySpecifier
)[];
export type subscription_rootFieldPolicy = {
  messages?: FieldPolicy<any> | FieldReadFunction<any>;
  messages_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  messages_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  threads?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
  users?: FieldPolicy<any> | FieldReadFunction<any>;
  users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  users_by_pk?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threadsKeySpecifier = (
  | "created_at"
  | "created_by"
  | "id"
  | "messages"
  | "messages_aggregate"
  | "threads_users"
  | "threads_users_aggregate"
  | "updated_at"
  | "user"
  | threadsKeySpecifier
)[];
export type threadsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  messages?: FieldPolicy<any> | FieldReadFunction<any>;
  messages_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
  user?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_aggregateKeySpecifier = (
  | "aggregate"
  | "nodes"
  | threads_aggregateKeySpecifier
)[];
export type threads_aggregateFieldPolicy = {
  aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  nodes?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_aggregate_fieldsKeySpecifier = (
  | "avg"
  | "count"
  | "max"
  | "min"
  | "stddev"
  | "stddev_pop"
  | "stddev_samp"
  | "sum"
  | "var_pop"
  | "var_samp"
  | "variance"
  | threads_aggregate_fieldsKeySpecifier
)[];
export type threads_aggregate_fieldsFieldPolicy = {
  avg?: FieldPolicy<any> | FieldReadFunction<any>;
  count?: FieldPolicy<any> | FieldReadFunction<any>;
  max?: FieldPolicy<any> | FieldReadFunction<any>;
  min?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  sum?: FieldPolicy<any> | FieldReadFunction<any>;
  var_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  var_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  variance?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_avg_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_avg_fieldsKeySpecifier
)[];
export type threads_avg_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_max_fieldsKeySpecifier = (
  | "created_at"
  | "created_by"
  | "id"
  | "updated_at"
  | threads_max_fieldsKeySpecifier
)[];
export type threads_max_fieldsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_min_fieldsKeySpecifier = (
  | "created_at"
  | "created_by"
  | "id"
  | "updated_at"
  | threads_min_fieldsKeySpecifier
)[];
export type threads_min_fieldsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_mutation_responseKeySpecifier = (
  | "affected_rows"
  | "returning"
  | threads_mutation_responseKeySpecifier
)[];
export type threads_mutation_responseFieldPolicy = {
  affected_rows?: FieldPolicy<any> | FieldReadFunction<any>;
  returning?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_stddev_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_stddev_fieldsKeySpecifier
)[];
export type threads_stddev_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_stddev_pop_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_stddev_pop_fieldsKeySpecifier
)[];
export type threads_stddev_pop_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_stddev_samp_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_stddev_samp_fieldsKeySpecifier
)[];
export type threads_stddev_samp_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_sum_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_sum_fieldsKeySpecifier
)[];
export type threads_sum_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_usersKeySpecifier = (
  | "created_at"
  | "id"
  | "thread"
  | "thread_id"
  | "updated_at"
  | "user"
  | "user_id"
  | threads_usersKeySpecifier
)[];
export type threads_usersFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
  user?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_aggregateKeySpecifier = (
  | "aggregate"
  | "nodes"
  | threads_users_aggregateKeySpecifier
)[];
export type threads_users_aggregateFieldPolicy = {
  aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  nodes?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_aggregate_fieldsKeySpecifier = (
  | "avg"
  | "count"
  | "max"
  | "min"
  | "stddev"
  | "stddev_pop"
  | "stddev_samp"
  | "sum"
  | "var_pop"
  | "var_samp"
  | "variance"
  | threads_users_aggregate_fieldsKeySpecifier
)[];
export type threads_users_aggregate_fieldsFieldPolicy = {
  avg?: FieldPolicy<any> | FieldReadFunction<any>;
  count?: FieldPolicy<any> | FieldReadFunction<any>;
  max?: FieldPolicy<any> | FieldReadFunction<any>;
  min?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  sum?: FieldPolicy<any> | FieldReadFunction<any>;
  var_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  var_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  variance?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_avg_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_avg_fieldsKeySpecifier
)[];
export type threads_users_avg_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_max_fieldsKeySpecifier = (
  | "created_at"
  | "id"
  | "thread_id"
  | "updated_at"
  | "user_id"
  | threads_users_max_fieldsKeySpecifier
)[];
export type threads_users_max_fieldsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_min_fieldsKeySpecifier = (
  | "created_at"
  | "id"
  | "thread_id"
  | "updated_at"
  | "user_id"
  | threads_users_min_fieldsKeySpecifier
)[];
export type threads_users_min_fieldsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_mutation_responseKeySpecifier = (
  | "affected_rows"
  | "returning"
  | threads_users_mutation_responseKeySpecifier
)[];
export type threads_users_mutation_responseFieldPolicy = {
  affected_rows?: FieldPolicy<any> | FieldReadFunction<any>;
  returning?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_stddev_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_stddev_fieldsKeySpecifier
)[];
export type threads_users_stddev_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_stddev_pop_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_stddev_pop_fieldsKeySpecifier
)[];
export type threads_users_stddev_pop_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_stddev_samp_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_stddev_samp_fieldsKeySpecifier
)[];
export type threads_users_stddev_samp_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_sum_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_sum_fieldsKeySpecifier
)[];
export type threads_users_sum_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_var_pop_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_var_pop_fieldsKeySpecifier
)[];
export type threads_users_var_pop_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_var_samp_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_var_samp_fieldsKeySpecifier
)[];
export type threads_users_var_samp_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_users_variance_fieldsKeySpecifier = (
  | "id"
  | "thread_id"
  | "user_id"
  | threads_users_variance_fieldsKeySpecifier
)[];
export type threads_users_variance_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  thread_id?: FieldPolicy<any> | FieldReadFunction<any>;
  user_id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_var_pop_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_var_pop_fieldsKeySpecifier
)[];
export type threads_var_pop_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_var_samp_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_var_samp_fieldsKeySpecifier
)[];
export type threads_var_samp_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type threads_variance_fieldsKeySpecifier = (
  | "created_by"
  | "id"
  | threads_variance_fieldsKeySpecifier
)[];
export type threads_variance_fieldsFieldPolicy = {
  created_by?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type usersKeySpecifier = (
  | "created_at"
  | "email"
  | "id"
  | "image_url"
  | "messages"
  | "messages_aggregate"
  | "name"
  | "threads"
  | "threads_aggregate"
  | "threads_users"
  | "threads_users_aggregate"
  | "updated_at"
  | usersKeySpecifier
)[];
export type usersFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  email?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  image_url?: FieldPolicy<any> | FieldReadFunction<any>;
  messages?: FieldPolicy<any> | FieldReadFunction<any>;
  messages_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  name?: FieldPolicy<any> | FieldReadFunction<any>;
  threads?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users?: FieldPolicy<any> | FieldReadFunction<any>;
  threads_users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_aggregateKeySpecifier = (
  | "aggregate"
  | "nodes"
  | users_aggregateKeySpecifier
)[];
export type users_aggregateFieldPolicy = {
  aggregate?: FieldPolicy<any> | FieldReadFunction<any>;
  nodes?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_aggregate_fieldsKeySpecifier = (
  | "avg"
  | "count"
  | "max"
  | "min"
  | "stddev"
  | "stddev_pop"
  | "stddev_samp"
  | "sum"
  | "var_pop"
  | "var_samp"
  | "variance"
  | users_aggregate_fieldsKeySpecifier
)[];
export type users_aggregate_fieldsFieldPolicy = {
  avg?: FieldPolicy<any> | FieldReadFunction<any>;
  count?: FieldPolicy<any> | FieldReadFunction<any>;
  max?: FieldPolicy<any> | FieldReadFunction<any>;
  min?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  sum?: FieldPolicy<any> | FieldReadFunction<any>;
  var_pop?: FieldPolicy<any> | FieldReadFunction<any>;
  var_samp?: FieldPolicy<any> | FieldReadFunction<any>;
  variance?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_avg_fieldsKeySpecifier = (
  | "id"
  | users_avg_fieldsKeySpecifier
)[];
export type users_avg_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_max_fieldsKeySpecifier = (
  | "created_at"
  | "email"
  | "id"
  | "image_url"
  | "name"
  | "updated_at"
  | users_max_fieldsKeySpecifier
)[];
export type users_max_fieldsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  email?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  image_url?: FieldPolicy<any> | FieldReadFunction<any>;
  name?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_min_fieldsKeySpecifier = (
  | "created_at"
  | "email"
  | "id"
  | "image_url"
  | "name"
  | "updated_at"
  | users_min_fieldsKeySpecifier
)[];
export type users_min_fieldsFieldPolicy = {
  created_at?: FieldPolicy<any> | FieldReadFunction<any>;
  email?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  image_url?: FieldPolicy<any> | FieldReadFunction<any>;
  name?: FieldPolicy<any> | FieldReadFunction<any>;
  updated_at?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_mutation_responseKeySpecifier = (
  | "affected_rows"
  | "returning"
  | users_mutation_responseKeySpecifier
)[];
export type users_mutation_responseFieldPolicy = {
  affected_rows?: FieldPolicy<any> | FieldReadFunction<any>;
  returning?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_stddev_fieldsKeySpecifier = (
  | "id"
  | users_stddev_fieldsKeySpecifier
)[];
export type users_stddev_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_stddev_pop_fieldsKeySpecifier = (
  | "id"
  | users_stddev_pop_fieldsKeySpecifier
)[];
export type users_stddev_pop_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_stddev_samp_fieldsKeySpecifier = (
  | "id"
  | users_stddev_samp_fieldsKeySpecifier
)[];
export type users_stddev_samp_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_sum_fieldsKeySpecifier = (
  | "id"
  | users_sum_fieldsKeySpecifier
)[];
export type users_sum_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_var_pop_fieldsKeySpecifier = (
  | "id"
  | users_var_pop_fieldsKeySpecifier
)[];
export type users_var_pop_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_var_samp_fieldsKeySpecifier = (
  | "id"
  | users_var_samp_fieldsKeySpecifier
)[];
export type users_var_samp_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type users_variance_fieldsKeySpecifier = (
  | "id"
  | users_variance_fieldsKeySpecifier
)[];
export type users_variance_fieldsFieldPolicy = {
  id?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type StrictTypedTypePolicies = {
  messages?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messagesKeySpecifier
      | (() => undefined | messagesKeySpecifier);
    fields?: messagesFieldPolicy;
  };
  messages_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_aggregateKeySpecifier
      | (() => undefined | messages_aggregateKeySpecifier);
    fields?: messages_aggregateFieldPolicy;
  };
  messages_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_aggregate_fieldsKeySpecifier
      | (() => undefined | messages_aggregate_fieldsKeySpecifier);
    fields?: messages_aggregate_fieldsFieldPolicy;
  };
  messages_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_avg_fieldsKeySpecifier
      | (() => undefined | messages_avg_fieldsKeySpecifier);
    fields?: messages_avg_fieldsFieldPolicy;
  };
  messages_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_max_fieldsKeySpecifier
      | (() => undefined | messages_max_fieldsKeySpecifier);
    fields?: messages_max_fieldsFieldPolicy;
  };
  messages_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_min_fieldsKeySpecifier
      | (() => undefined | messages_min_fieldsKeySpecifier);
    fields?: messages_min_fieldsFieldPolicy;
  };
  messages_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_mutation_responseKeySpecifier
      | (() => undefined | messages_mutation_responseKeySpecifier);
    fields?: messages_mutation_responseFieldPolicy;
  };
  messages_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_stddev_fieldsKeySpecifier
      | (() => undefined | messages_stddev_fieldsKeySpecifier);
    fields?: messages_stddev_fieldsFieldPolicy;
  };
  messages_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_stddev_pop_fieldsKeySpecifier
      | (() => undefined | messages_stddev_pop_fieldsKeySpecifier);
    fields?: messages_stddev_pop_fieldsFieldPolicy;
  };
  messages_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_stddev_samp_fieldsKeySpecifier
      | (() => undefined | messages_stddev_samp_fieldsKeySpecifier);
    fields?: messages_stddev_samp_fieldsFieldPolicy;
  };
  messages_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_sum_fieldsKeySpecifier
      | (() => undefined | messages_sum_fieldsKeySpecifier);
    fields?: messages_sum_fieldsFieldPolicy;
  };
  messages_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_var_pop_fieldsKeySpecifier
      | (() => undefined | messages_var_pop_fieldsKeySpecifier);
    fields?: messages_var_pop_fieldsFieldPolicy;
  };
  messages_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_var_samp_fieldsKeySpecifier
      | (() => undefined | messages_var_samp_fieldsKeySpecifier);
    fields?: messages_var_samp_fieldsFieldPolicy;
  };
  messages_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | messages_variance_fieldsKeySpecifier
      | (() => undefined | messages_variance_fieldsKeySpecifier);
    fields?: messages_variance_fieldsFieldPolicy;
  };
  mutation_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | mutation_rootKeySpecifier
      | (() => undefined | mutation_rootKeySpecifier);
    fields?: mutation_rootFieldPolicy;
  };
  query_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | query_rootKeySpecifier
      | (() => undefined | query_rootKeySpecifier);
    fields?: query_rootFieldPolicy;
  };
  subscription_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | subscription_rootKeySpecifier
      | (() => undefined | subscription_rootKeySpecifier);
    fields?: subscription_rootFieldPolicy;
  };
  threads?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threadsKeySpecifier
      | (() => undefined | threadsKeySpecifier);
    fields?: threadsFieldPolicy;
  };
  threads_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_aggregateKeySpecifier
      | (() => undefined | threads_aggregateKeySpecifier);
    fields?: threads_aggregateFieldPolicy;
  };
  threads_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_aggregate_fieldsKeySpecifier
      | (() => undefined | threads_aggregate_fieldsKeySpecifier);
    fields?: threads_aggregate_fieldsFieldPolicy;
  };
  threads_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_avg_fieldsKeySpecifier
      | (() => undefined | threads_avg_fieldsKeySpecifier);
    fields?: threads_avg_fieldsFieldPolicy;
  };
  threads_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_max_fieldsKeySpecifier
      | (() => undefined | threads_max_fieldsKeySpecifier);
    fields?: threads_max_fieldsFieldPolicy;
  };
  threads_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_min_fieldsKeySpecifier
      | (() => undefined | threads_min_fieldsKeySpecifier);
    fields?: threads_min_fieldsFieldPolicy;
  };
  threads_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_mutation_responseKeySpecifier
      | (() => undefined | threads_mutation_responseKeySpecifier);
    fields?: threads_mutation_responseFieldPolicy;
  };
  threads_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_stddev_fieldsKeySpecifier
      | (() => undefined | threads_stddev_fieldsKeySpecifier);
    fields?: threads_stddev_fieldsFieldPolicy;
  };
  threads_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_stddev_pop_fieldsKeySpecifier
      | (() => undefined | threads_stddev_pop_fieldsKeySpecifier);
    fields?: threads_stddev_pop_fieldsFieldPolicy;
  };
  threads_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_stddev_samp_fieldsKeySpecifier
      | (() => undefined | threads_stddev_samp_fieldsKeySpecifier);
    fields?: threads_stddev_samp_fieldsFieldPolicy;
  };
  threads_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_sum_fieldsKeySpecifier
      | (() => undefined | threads_sum_fieldsKeySpecifier);
    fields?: threads_sum_fieldsFieldPolicy;
  };
  threads_users?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_usersKeySpecifier
      | (() => undefined | threads_usersKeySpecifier);
    fields?: threads_usersFieldPolicy;
  };
  threads_users_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_aggregateKeySpecifier
      | (() => undefined | threads_users_aggregateKeySpecifier);
    fields?: threads_users_aggregateFieldPolicy;
  };
  threads_users_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_aggregate_fieldsKeySpecifier
      | (() => undefined | threads_users_aggregate_fieldsKeySpecifier);
    fields?: threads_users_aggregate_fieldsFieldPolicy;
  };
  threads_users_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_avg_fieldsKeySpecifier
      | (() => undefined | threads_users_avg_fieldsKeySpecifier);
    fields?: threads_users_avg_fieldsFieldPolicy;
  };
  threads_users_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_max_fieldsKeySpecifier
      | (() => undefined | threads_users_max_fieldsKeySpecifier);
    fields?: threads_users_max_fieldsFieldPolicy;
  };
  threads_users_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_min_fieldsKeySpecifier
      | (() => undefined | threads_users_min_fieldsKeySpecifier);
    fields?: threads_users_min_fieldsFieldPolicy;
  };
  threads_users_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_mutation_responseKeySpecifier
      | (() => undefined | threads_users_mutation_responseKeySpecifier);
    fields?: threads_users_mutation_responseFieldPolicy;
  };
  threads_users_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_stddev_fieldsKeySpecifier
      | (() => undefined | threads_users_stddev_fieldsKeySpecifier);
    fields?: threads_users_stddev_fieldsFieldPolicy;
  };
  threads_users_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_stddev_pop_fieldsKeySpecifier
      | (() => undefined | threads_users_stddev_pop_fieldsKeySpecifier);
    fields?: threads_users_stddev_pop_fieldsFieldPolicy;
  };
  threads_users_stddev_samp_fields?: Omit<
    TypePolicy,
    "fields" | "keyFields"
  > & {
    keyFields?:
      | false
      | threads_users_stddev_samp_fieldsKeySpecifier
      | (() => undefined | threads_users_stddev_samp_fieldsKeySpecifier);
    fields?: threads_users_stddev_samp_fieldsFieldPolicy;
  };
  threads_users_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_sum_fieldsKeySpecifier
      | (() => undefined | threads_users_sum_fieldsKeySpecifier);
    fields?: threads_users_sum_fieldsFieldPolicy;
  };
  threads_users_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_var_pop_fieldsKeySpecifier
      | (() => undefined | threads_users_var_pop_fieldsKeySpecifier);
    fields?: threads_users_var_pop_fieldsFieldPolicy;
  };
  threads_users_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_var_samp_fieldsKeySpecifier
      | (() => undefined | threads_users_var_samp_fieldsKeySpecifier);
    fields?: threads_users_var_samp_fieldsFieldPolicy;
  };
  threads_users_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_users_variance_fieldsKeySpecifier
      | (() => undefined | threads_users_variance_fieldsKeySpecifier);
    fields?: threads_users_variance_fieldsFieldPolicy;
  };
  threads_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_var_pop_fieldsKeySpecifier
      | (() => undefined | threads_var_pop_fieldsKeySpecifier);
    fields?: threads_var_pop_fieldsFieldPolicy;
  };
  threads_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_var_samp_fieldsKeySpecifier
      | (() => undefined | threads_var_samp_fieldsKeySpecifier);
    fields?: threads_var_samp_fieldsFieldPolicy;
  };
  threads_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | threads_variance_fieldsKeySpecifier
      | (() => undefined | threads_variance_fieldsKeySpecifier);
    fields?: threads_variance_fieldsFieldPolicy;
  };
  users?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | usersKeySpecifier
      | (() => undefined | usersKeySpecifier);
    fields?: usersFieldPolicy;
  };
  users_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_aggregateKeySpecifier
      | (() => undefined | users_aggregateKeySpecifier);
    fields?: users_aggregateFieldPolicy;
  };
  users_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_aggregate_fieldsKeySpecifier
      | (() => undefined | users_aggregate_fieldsKeySpecifier);
    fields?: users_aggregate_fieldsFieldPolicy;
  };
  users_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_avg_fieldsKeySpecifier
      | (() => undefined | users_avg_fieldsKeySpecifier);
    fields?: users_avg_fieldsFieldPolicy;
  };
  users_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_max_fieldsKeySpecifier
      | (() => undefined | users_max_fieldsKeySpecifier);
    fields?: users_max_fieldsFieldPolicy;
  };
  users_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_min_fieldsKeySpecifier
      | (() => undefined | users_min_fieldsKeySpecifier);
    fields?: users_min_fieldsFieldPolicy;
  };
  users_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_mutation_responseKeySpecifier
      | (() => undefined | users_mutation_responseKeySpecifier);
    fields?: users_mutation_responseFieldPolicy;
  };
  users_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_stddev_fieldsKeySpecifier
      | (() => undefined | users_stddev_fieldsKeySpecifier);
    fields?: users_stddev_fieldsFieldPolicy;
  };
  users_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_stddev_pop_fieldsKeySpecifier
      | (() => undefined | users_stddev_pop_fieldsKeySpecifier);
    fields?: users_stddev_pop_fieldsFieldPolicy;
  };
  users_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_stddev_samp_fieldsKeySpecifier
      | (() => undefined | users_stddev_samp_fieldsKeySpecifier);
    fields?: users_stddev_samp_fieldsFieldPolicy;
  };
  users_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_sum_fieldsKeySpecifier
      | (() => undefined | users_sum_fieldsKeySpecifier);
    fields?: users_sum_fieldsFieldPolicy;
  };
  users_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_var_pop_fieldsKeySpecifier
      | (() => undefined | users_var_pop_fieldsKeySpecifier);
    fields?: users_var_pop_fieldsFieldPolicy;
  };
  users_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_var_samp_fieldsKeySpecifier
      | (() => undefined | users_var_samp_fieldsKeySpecifier);
    fields?: users_var_samp_fieldsFieldPolicy;
  };
  users_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | users_variance_fieldsKeySpecifier
      | (() => undefined | users_variance_fieldsKeySpecifier);
    fields?: users_variance_fieldsFieldPolicy;
  };
};
export type TypedTypePolicies = StrictTypedTypePolicies & TypePolicies;
