/* eslint-disable */
// @generated by graphql-codegen
// This file was automatically generated and should not be edited.
import { FieldPolicy, FieldReadFunction, TypePolicies, TypePolicy } from '@apollo/client/cache';
export type Auth0OutputKeySpecifier = ('accessToken' | Auth0OutputKeySpecifier)[];
export type Auth0OutputFieldPolicy = {
	accessToken?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLoginKeySpecifier = ('id' | 'ipAddress' | 'timestamp' | 'user' | 'userId' | activityLoginKeySpecifier)[];
export type activityLoginFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	ipAddress?: FieldPolicy<any> | FieldReadFunction<any>,
	timestamp?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_aggregateKeySpecifier = ('aggregate' | 'nodes' | activityLogin_aggregateKeySpecifier)[];
export type activityLogin_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | activityLogin_aggregate_fieldsKeySpecifier)[];
export type activityLogin_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_avg_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_avg_fieldsKeySpecifier)[];
export type activityLogin_avg_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_max_fieldsKeySpecifier = ('id' | 'ipAddress' | 'timestamp' | 'userId' | activityLogin_max_fieldsKeySpecifier)[];
export type activityLogin_max_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	ipAddress?: FieldPolicy<any> | FieldReadFunction<any>,
	timestamp?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_min_fieldsKeySpecifier = ('id' | 'ipAddress' | 'timestamp' | 'userId' | activityLogin_min_fieldsKeySpecifier)[];
export type activityLogin_min_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	ipAddress?: FieldPolicy<any> | FieldReadFunction<any>,
	timestamp?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | activityLogin_mutation_responseKeySpecifier)[];
export type activityLogin_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_stddev_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_stddev_fieldsKeySpecifier)[];
export type activityLogin_stddev_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_stddev_pop_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_stddev_pop_fieldsKeySpecifier)[];
export type activityLogin_stddev_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_stddev_samp_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_stddev_samp_fieldsKeySpecifier)[];
export type activityLogin_stddev_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_sum_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_sum_fieldsKeySpecifier)[];
export type activityLogin_sum_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_var_pop_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_var_pop_fieldsKeySpecifier)[];
export type activityLogin_var_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_var_samp_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_var_samp_fieldsKeySpecifier)[];
export type activityLogin_var_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type activityLogin_variance_fieldsKeySpecifier = ('id' | 'userId' | activityLogin_variance_fieldsKeySpecifier)[];
export type activityLogin_variance_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type courseKeySpecifier = ('content' | 'createdAt' | 'createdById' | 'id' | 'premium' | 'price' | 'sku' | 'slug' | 'status' | 'summary' | 'title' | 'updatedAt' | 'updatedById' | 'user' | 'userByCreatedById' | courseKeySpecifier)[];
export type courseFieldPolicy = {
	content?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	premium?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	sku?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	summary?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userByCreatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_aggregateKeySpecifier = ('aggregate' | 'nodes' | course_aggregateKeySpecifier)[];
export type course_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | course_aggregate_fieldsKeySpecifier)[];
export type course_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_avg_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_avg_fieldsKeySpecifier)[];
export type course_avg_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_max_fieldsKeySpecifier = ('content' | 'createdAt' | 'createdById' | 'id' | 'price' | 'sku' | 'slug' | 'status' | 'summary' | 'title' | 'updatedAt' | 'updatedById' | course_max_fieldsKeySpecifier)[];
export type course_max_fieldsFieldPolicy = {
	content?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	sku?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	summary?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_min_fieldsKeySpecifier = ('content' | 'createdAt' | 'createdById' | 'id' | 'price' | 'sku' | 'slug' | 'status' | 'summary' | 'title' | 'updatedAt' | 'updatedById' | course_min_fieldsKeySpecifier)[];
export type course_min_fieldsFieldPolicy = {
	content?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	sku?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	summary?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | course_mutation_responseKeySpecifier)[];
export type course_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_stddev_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_stddev_fieldsKeySpecifier)[];
export type course_stddev_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_stddev_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_stddev_pop_fieldsKeySpecifier)[];
export type course_stddev_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_stddev_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_stddev_samp_fieldsKeySpecifier)[];
export type course_stddev_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_sum_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_sum_fieldsKeySpecifier)[];
export type course_sum_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_var_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_var_pop_fieldsKeySpecifier)[];
export type course_var_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_var_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_var_samp_fieldsKeySpecifier)[];
export type course_var_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type course_variance_fieldsKeySpecifier = ('createdById' | 'id' | 'price' | 'updatedById' | course_variance_fieldsKeySpecifier)[];
export type course_variance_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	price?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type mutation_rootKeySpecifier = ('activityLoginDelete' | 'activityLoginInsert' | 'activityLoginUpdate' | 'activityLoginsDelete' | 'activityLoginsInsert' | 'activityLoginsUpdate' | 'courseDelete' | 'courseInsert' | 'courseUpdate' | 'coursesDelete' | 'coursesInsert' | 'coursesUpdate' | 'createAuth0User' | 'pageDelete' | 'pageInsert' | 'pageUpdate' | 'pagesDelete' | 'pagesInsert' | 'pagesUpdate' | 'postDelete' | 'postInsert' | 'postUpdate' | 'postsDelete' | 'postsInsert' | 'postsUpdate' | 'profileDelete' | 'profileInsert' | 'profileUpdate' | 'profilesDelete' | 'profilesInsert' | 'profilesUpdate' | 'roleDelete' | 'roleInsert' | 'roleUpdate' | 'rolesDelete' | 'rolesInsert' | 'rolesUpdate' | 'tagDelete' | 'tagInsert' | 'tagUpdate' | 'tagsDelete' | 'tagsInsert' | 'tagsUpdate' | 'topicDelete' | 'topicInsert' | 'topicUpdate' | 'topicsDelete' | 'topicsInsert' | 'topicsUpdate' | 'userDelete' | 'userInsert' | 'userUpdate' | 'usersDelete' | 'usersInsert' | 'usersUpdate' | mutation_rootKeySpecifier)[];
export type mutation_rootFieldPolicy = {
	activityLoginDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginsDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginsInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginsUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	courseDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	courseInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	courseUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	createAuth0User?: FieldPolicy<any> | FieldReadFunction<any>,
	pageDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	pageInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	pageUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	postDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	postInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	postUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	postsDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	postsInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	postsUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	profileDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	profileInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	profileUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	profilesDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	profilesInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	profilesUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	roleDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	roleInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	roleUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	rolesDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	rolesInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	rolesUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	tagDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	tagInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	tagUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	topicDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	topicInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	topicUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	userDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	userInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	userUpdate?: FieldPolicy<any> | FieldReadFunction<any>,
	usersDelete?: FieldPolicy<any> | FieldReadFunction<any>,
	usersInsert?: FieldPolicy<any> | FieldReadFunction<any>,
	usersUpdate?: FieldPolicy<any> | FieldReadFunction<any>
};
export type pageKeySpecifier = ('body' | 'createdAt' | 'createdById' | 'id' | 'slug' | 'status' | 'title' | 'updatedAt' | 'updatedById' | 'user' | 'userByUpdatedById' | pageKeySpecifier)[];
export type pageFieldPolicy = {
	body?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_aggregateKeySpecifier = ('aggregate' | 'nodes' | page_aggregateKeySpecifier)[];
export type page_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | page_aggregate_fieldsKeySpecifier)[];
export type page_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_avg_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_avg_fieldsKeySpecifier)[];
export type page_avg_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_max_fieldsKeySpecifier = ('body' | 'createdAt' | 'createdById' | 'id' | 'slug' | 'status' | 'title' | 'updatedAt' | 'updatedById' | page_max_fieldsKeySpecifier)[];
export type page_max_fieldsFieldPolicy = {
	body?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_min_fieldsKeySpecifier = ('body' | 'createdAt' | 'createdById' | 'id' | 'slug' | 'status' | 'title' | 'updatedAt' | 'updatedById' | page_min_fieldsKeySpecifier)[];
export type page_min_fieldsFieldPolicy = {
	body?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | page_mutation_responseKeySpecifier)[];
export type page_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_stddev_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_stddev_fieldsKeySpecifier)[];
export type page_stddev_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_stddev_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_stddev_pop_fieldsKeySpecifier)[];
export type page_stddev_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_stddev_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_stddev_samp_fieldsKeySpecifier)[];
export type page_stddev_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_sum_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_sum_fieldsKeySpecifier)[];
export type page_sum_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_var_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_var_pop_fieldsKeySpecifier)[];
export type page_var_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_var_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_var_samp_fieldsKeySpecifier)[];
export type page_var_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_variance_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | page_variance_fieldsKeySpecifier)[];
export type page_variance_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type postKeySpecifier = ('content' | 'createdAt' | 'createdById' | 'id' | 'slug' | 'status' | 'summary' | 'tagIds' | 'title' | 'topicIds' | 'updatedAt' | 'updatedById' | 'userByCreatedById' | 'userByUpdatedById' | postKeySpecifier)[];
export type postFieldPolicy = {
	content?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	summary?: FieldPolicy<any> | FieldReadFunction<any>,
	tagIds?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	topicIds?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	userByCreatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	userByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_aggregateKeySpecifier = ('aggregate' | 'nodes' | post_aggregateKeySpecifier)[];
export type post_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | post_aggregate_fieldsKeySpecifier)[];
export type post_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_avg_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_avg_fieldsKeySpecifier)[];
export type post_avg_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_max_fieldsKeySpecifier = ('content' | 'createdAt' | 'createdById' | 'id' | 'slug' | 'status' | 'summary' | 'title' | 'updatedAt' | 'updatedById' | post_max_fieldsKeySpecifier)[];
export type post_max_fieldsFieldPolicy = {
	content?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	summary?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_min_fieldsKeySpecifier = ('content' | 'createdAt' | 'createdById' | 'id' | 'slug' | 'status' | 'summary' | 'title' | 'updatedAt' | 'updatedById' | post_min_fieldsKeySpecifier)[];
export type post_min_fieldsFieldPolicy = {
	content?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	summary?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | post_mutation_responseKeySpecifier)[];
export type post_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_stddev_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_stddev_fieldsKeySpecifier)[];
export type post_stddev_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_stddev_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_stddev_pop_fieldsKeySpecifier)[];
export type post_stddev_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_stddev_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_stddev_samp_fieldsKeySpecifier)[];
export type post_stddev_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_sum_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_sum_fieldsKeySpecifier)[];
export type post_sum_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_var_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_var_pop_fieldsKeySpecifier)[];
export type post_var_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_var_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_var_samp_fieldsKeySpecifier)[];
export type post_var_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type post_variance_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | post_variance_fieldsKeySpecifier)[];
export type post_variance_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profileKeySpecifier = ('avatarUrl' | 'biography' | 'id' | 'isPublic' | 'links' | 'location' | 'phoneNumber' | 'phoneVerified' | 'slug' | 'user' | 'userId' | profileKeySpecifier)[];
export type profileFieldPolicy = {
	avatarUrl?: FieldPolicy<any> | FieldReadFunction<any>,
	biography?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	isPublic?: FieldPolicy<any> | FieldReadFunction<any>,
	links?: FieldPolicy<any> | FieldReadFunction<any>,
	location?: FieldPolicy<any> | FieldReadFunction<any>,
	phoneNumber?: FieldPolicy<any> | FieldReadFunction<any>,
	phoneVerified?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_aggregateKeySpecifier = ('aggregate' | 'nodes' | profile_aggregateKeySpecifier)[];
export type profile_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | profile_aggregate_fieldsKeySpecifier)[];
export type profile_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_avg_fieldsKeySpecifier = ('id' | 'userId' | profile_avg_fieldsKeySpecifier)[];
export type profile_avg_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_max_fieldsKeySpecifier = ('avatarUrl' | 'biography' | 'id' | 'location' | 'phoneNumber' | 'slug' | 'userId' | profile_max_fieldsKeySpecifier)[];
export type profile_max_fieldsFieldPolicy = {
	avatarUrl?: FieldPolicy<any> | FieldReadFunction<any>,
	biography?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	location?: FieldPolicy<any> | FieldReadFunction<any>,
	phoneNumber?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_min_fieldsKeySpecifier = ('avatarUrl' | 'biography' | 'id' | 'location' | 'phoneNumber' | 'slug' | 'userId' | profile_min_fieldsKeySpecifier)[];
export type profile_min_fieldsFieldPolicy = {
	avatarUrl?: FieldPolicy<any> | FieldReadFunction<any>,
	biography?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	location?: FieldPolicy<any> | FieldReadFunction<any>,
	phoneNumber?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | profile_mutation_responseKeySpecifier)[];
export type profile_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_stddev_fieldsKeySpecifier = ('id' | 'userId' | profile_stddev_fieldsKeySpecifier)[];
export type profile_stddev_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_stddev_pop_fieldsKeySpecifier = ('id' | 'userId' | profile_stddev_pop_fieldsKeySpecifier)[];
export type profile_stddev_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_stddev_samp_fieldsKeySpecifier = ('id' | 'userId' | profile_stddev_samp_fieldsKeySpecifier)[];
export type profile_stddev_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_sum_fieldsKeySpecifier = ('id' | 'userId' | profile_sum_fieldsKeySpecifier)[];
export type profile_sum_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_var_pop_fieldsKeySpecifier = ('id' | 'userId' | profile_var_pop_fieldsKeySpecifier)[];
export type profile_var_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_var_samp_fieldsKeySpecifier = ('id' | 'userId' | profile_var_samp_fieldsKeySpecifier)[];
export type profile_var_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type profile_variance_fieldsKeySpecifier = ('id' | 'userId' | profile_variance_fieldsKeySpecifier)[];
export type profile_variance_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	userId?: FieldPolicy<any> | FieldReadFunction<any>
};
export type query_rootKeySpecifier = ('activityLogin' | 'activityLogins' | 'activityLoginsAggregate' | 'course' | 'courses' | 'coursesAggregate' | 'page' | 'pages' | 'pagesAggregate' | 'post' | 'posts' | 'postsAggregate' | 'profile' | 'profiles' | 'profilesAggregate' | 'role' | 'roles' | 'rolesAggregate' | 'tag' | 'tags' | 'tagsAggregate' | 'topic' | 'topics' | 'topicsAggregate' | 'user' | 'users' | 'usersAggregate' | query_rootKeySpecifier)[];
export type query_rootFieldPolicy = {
	activityLogin?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLogins?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	course?: FieldPolicy<any> | FieldReadFunction<any>,
	courses?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	page?: FieldPolicy<any> | FieldReadFunction<any>,
	pages?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	post?: FieldPolicy<any> | FieldReadFunction<any>,
	posts?: FieldPolicy<any> | FieldReadFunction<any>,
	postsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	profile?: FieldPolicy<any> | FieldReadFunction<any>,
	profiles?: FieldPolicy<any> | FieldReadFunction<any>,
	profilesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	role?: FieldPolicy<any> | FieldReadFunction<any>,
	roles?: FieldPolicy<any> | FieldReadFunction<any>,
	rolesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	tag?: FieldPolicy<any> | FieldReadFunction<any>,
	tags?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	topic?: FieldPolicy<any> | FieldReadFunction<any>,
	topics?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	users?: FieldPolicy<any> | FieldReadFunction<any>,
	usersAggregate?: FieldPolicy<any> | FieldReadFunction<any>
};
export type roleKeySpecifier = ('description' | 'id' | 'name' | 'type' | 'users' | 'users_aggregate' | roleKeySpecifier)[];
export type roleFieldPolicy = {
	description?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	name?: FieldPolicy<any> | FieldReadFunction<any>,
	type?: FieldPolicy<any> | FieldReadFunction<any>,
	users?: FieldPolicy<any> | FieldReadFunction<any>,
	users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_aggregateKeySpecifier = ('aggregate' | 'nodes' | role_aggregateKeySpecifier)[];
export type role_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | role_aggregate_fieldsKeySpecifier)[];
export type role_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_avg_fieldsKeySpecifier = ('id' | role_avg_fieldsKeySpecifier)[];
export type role_avg_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_max_fieldsKeySpecifier = ('description' | 'id' | 'name' | 'type' | role_max_fieldsKeySpecifier)[];
export type role_max_fieldsFieldPolicy = {
	description?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	name?: FieldPolicy<any> | FieldReadFunction<any>,
	type?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_min_fieldsKeySpecifier = ('description' | 'id' | 'name' | 'type' | role_min_fieldsKeySpecifier)[];
export type role_min_fieldsFieldPolicy = {
	description?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	name?: FieldPolicy<any> | FieldReadFunction<any>,
	type?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | role_mutation_responseKeySpecifier)[];
export type role_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_stddev_fieldsKeySpecifier = ('id' | role_stddev_fieldsKeySpecifier)[];
export type role_stddev_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_stddev_pop_fieldsKeySpecifier = ('id' | role_stddev_pop_fieldsKeySpecifier)[];
export type role_stddev_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_stddev_samp_fieldsKeySpecifier = ('id' | role_stddev_samp_fieldsKeySpecifier)[];
export type role_stddev_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_sum_fieldsKeySpecifier = ('id' | role_sum_fieldsKeySpecifier)[];
export type role_sum_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_var_pop_fieldsKeySpecifier = ('id' | role_var_pop_fieldsKeySpecifier)[];
export type role_var_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_var_samp_fieldsKeySpecifier = ('id' | role_var_samp_fieldsKeySpecifier)[];
export type role_var_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type role_variance_fieldsKeySpecifier = ('id' | role_variance_fieldsKeySpecifier)[];
export type role_variance_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type subscription_rootKeySpecifier = ('activityLogin' | 'activityLogins' | 'activityLoginsAggregate' | 'course' | 'courses' | 'coursesAggregate' | 'page' | 'pages' | 'pagesAggregate' | 'post' | 'posts' | 'postsAggregate' | 'profile' | 'profiles' | 'profilesAggregate' | 'role' | 'roles' | 'rolesAggregate' | 'tag' | 'tags' | 'tagsAggregate' | 'topic' | 'topics' | 'topicsAggregate' | 'user' | 'users' | 'usersAggregate' | subscription_rootKeySpecifier)[];
export type subscription_rootFieldPolicy = {
	activityLogin?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLogins?: FieldPolicy<any> | FieldReadFunction<any>,
	activityLoginsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	course?: FieldPolicy<any> | FieldReadFunction<any>,
	courses?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	page?: FieldPolicy<any> | FieldReadFunction<any>,
	pages?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	post?: FieldPolicy<any> | FieldReadFunction<any>,
	posts?: FieldPolicy<any> | FieldReadFunction<any>,
	postsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	profile?: FieldPolicy<any> | FieldReadFunction<any>,
	profiles?: FieldPolicy<any> | FieldReadFunction<any>,
	profilesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	role?: FieldPolicy<any> | FieldReadFunction<any>,
	roles?: FieldPolicy<any> | FieldReadFunction<any>,
	rolesAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	tag?: FieldPolicy<any> | FieldReadFunction<any>,
	tags?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	topic?: FieldPolicy<any> | FieldReadFunction<any>,
	topics?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsAggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	users?: FieldPolicy<any> | FieldReadFunction<any>,
	usersAggregate?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tagKeySpecifier = ('createdAt' | 'createdById' | 'id' | 'slug' | 'title' | 'updatedAt' | 'updatedById' | 'user' | 'userByUpdatedById' | tagKeySpecifier)[];
export type tagFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_aggregateKeySpecifier = ('aggregate' | 'nodes' | tag_aggregateKeySpecifier)[];
export type tag_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | tag_aggregate_fieldsKeySpecifier)[];
export type tag_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_avg_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_avg_fieldsKeySpecifier)[];
export type tag_avg_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_max_fieldsKeySpecifier = ('createdAt' | 'createdById' | 'id' | 'slug' | 'title' | 'updatedAt' | 'updatedById' | tag_max_fieldsKeySpecifier)[];
export type tag_max_fieldsFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_min_fieldsKeySpecifier = ('createdAt' | 'createdById' | 'id' | 'slug' | 'title' | 'updatedAt' | 'updatedById' | tag_min_fieldsKeySpecifier)[];
export type tag_min_fieldsFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | tag_mutation_responseKeySpecifier)[];
export type tag_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_stddev_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_stddev_fieldsKeySpecifier)[];
export type tag_stddev_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_stddev_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_stddev_pop_fieldsKeySpecifier)[];
export type tag_stddev_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_stddev_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_stddev_samp_fieldsKeySpecifier)[];
export type tag_stddev_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_sum_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_sum_fieldsKeySpecifier)[];
export type tag_sum_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_var_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_var_pop_fieldsKeySpecifier)[];
export type tag_var_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_var_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_var_samp_fieldsKeySpecifier)[];
export type tag_var_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type tag_variance_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | tag_variance_fieldsKeySpecifier)[];
export type tag_variance_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topicKeySpecifier = ('createdAt' | 'createdById' | 'id' | 'parentTopicIds' | 'slug' | 'title' | 'updatedAt' | 'updatedById' | 'user' | 'userByUpdatedById' | topicKeySpecifier)[];
export type topicFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	parentTopicIds?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_aggregateKeySpecifier = ('aggregate' | 'nodes' | topic_aggregateKeySpecifier)[];
export type topic_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | topic_aggregate_fieldsKeySpecifier)[];
export type topic_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_avg_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_avg_fieldsKeySpecifier)[];
export type topic_avg_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_max_fieldsKeySpecifier = ('createdAt' | 'createdById' | 'id' | 'slug' | 'title' | 'updatedAt' | 'updatedById' | topic_max_fieldsKeySpecifier)[];
export type topic_max_fieldsFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_min_fieldsKeySpecifier = ('createdAt' | 'createdById' | 'id' | 'slug' | 'title' | 'updatedAt' | 'updatedById' | topic_min_fieldsKeySpecifier)[];
export type topic_min_fieldsFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | topic_mutation_responseKeySpecifier)[];
export type topic_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_stddev_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_stddev_fieldsKeySpecifier)[];
export type topic_stddev_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_stddev_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_stddev_pop_fieldsKeySpecifier)[];
export type topic_stddev_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_stddev_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_stddev_samp_fieldsKeySpecifier)[];
export type topic_stddev_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_sum_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_sum_fieldsKeySpecifier)[];
export type topic_sum_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_var_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_var_pop_fieldsKeySpecifier)[];
export type topic_var_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_var_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_var_samp_fieldsKeySpecifier)[];
export type topic_var_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type topic_variance_fieldsKeySpecifier = ('createdById' | 'id' | 'updatedById' | topic_variance_fieldsKeySpecifier)[];
export type topic_variance_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type userKeySpecifier = ('courses' | 'coursesByUpdatedById' | 'coursesByUpdatedById_aggregate' | 'courses_aggregate' | 'createdAt' | 'createdById' | 'emailAddress' | 'firstName' | 'fullName' | 'id' | 'lastActive' | 'lastName' | 'logins' | 'logins_aggregate' | 'pages' | 'pagesByCreatedById' | 'pagesByCreatedById_aggregate' | 'pages_aggregate' | 'posts' | 'postsByUpdatedById' | 'postsByUpdatedById_aggregate' | 'posts_aggregate' | 'profile' | 'pronouns' | 'role' | 'roleId' | 'status' | 'tags' | 'tagsByUpdatedById' | 'tagsByUpdatedById_aggregate' | 'tags_aggregate' | 'topics' | 'topicsByUpdatedById' | 'topicsByUpdatedById_aggregate' | 'topics_aggregate' | 'updatedAt' | 'updatedById' | 'user' | 'userByUpdatedById' | 'username' | 'users' | 'usersByUpdatedById' | 'usersByUpdatedById_aggregate' | 'users_aggregate' | 'verified' | userKeySpecifier)[];
export type userFieldPolicy = {
	courses?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	coursesByUpdatedById_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	courses_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	emailAddress?: FieldPolicy<any> | FieldReadFunction<any>,
	firstName?: FieldPolicy<any> | FieldReadFunction<any>,
	fullName?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	lastActive?: FieldPolicy<any> | FieldReadFunction<any>,
	lastName?: FieldPolicy<any> | FieldReadFunction<any>,
	logins?: FieldPolicy<any> | FieldReadFunction<any>,
	logins_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	pages?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesByCreatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	pagesByCreatedById_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	pages_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	posts?: FieldPolicy<any> | FieldReadFunction<any>,
	postsByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	postsByUpdatedById_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	posts_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	profile?: FieldPolicy<any> | FieldReadFunction<any>,
	pronouns?: FieldPolicy<any> | FieldReadFunction<any>,
	role?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	tags?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	tagsByUpdatedById_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	tags_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	topics?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	topicsByUpdatedById_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	topics_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	user?: FieldPolicy<any> | FieldReadFunction<any>,
	userByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	username?: FieldPolicy<any> | FieldReadFunction<any>,
	users?: FieldPolicy<any> | FieldReadFunction<any>,
	usersByUpdatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	usersByUpdatedById_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	users_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	verified?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_aggregateKeySpecifier = ('aggregate' | 'nodes' | user_aggregateKeySpecifier)[];
export type user_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | user_aggregate_fieldsKeySpecifier)[];
export type user_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_avg_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_avg_fieldsKeySpecifier)[];
export type user_avg_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_max_fieldsKeySpecifier = ('createdAt' | 'createdById' | 'emailAddress' | 'firstName' | 'fullName' | 'id' | 'lastActive' | 'lastName' | 'pronouns' | 'roleId' | 'status' | 'updatedAt' | 'updatedById' | 'username' | user_max_fieldsKeySpecifier)[];
export type user_max_fieldsFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	emailAddress?: FieldPolicy<any> | FieldReadFunction<any>,
	firstName?: FieldPolicy<any> | FieldReadFunction<any>,
	fullName?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	lastActive?: FieldPolicy<any> | FieldReadFunction<any>,
	lastName?: FieldPolicy<any> | FieldReadFunction<any>,
	pronouns?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	username?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_min_fieldsKeySpecifier = ('createdAt' | 'createdById' | 'emailAddress' | 'firstName' | 'fullName' | 'id' | 'lastActive' | 'lastName' | 'pronouns' | 'roleId' | 'status' | 'updatedAt' | 'updatedById' | 'username' | user_min_fieldsKeySpecifier)[];
export type user_min_fieldsFieldPolicy = {
	createdAt?: FieldPolicy<any> | FieldReadFunction<any>,
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	emailAddress?: FieldPolicy<any> | FieldReadFunction<any>,
	firstName?: FieldPolicy<any> | FieldReadFunction<any>,
	fullName?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	lastActive?: FieldPolicy<any> | FieldReadFunction<any>,
	lastName?: FieldPolicy<any> | FieldReadFunction<any>,
	pronouns?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	status?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedAt?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>,
	username?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | user_mutation_responseKeySpecifier)[];
export type user_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_stddev_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_stddev_fieldsKeySpecifier)[];
export type user_stddev_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_stddev_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_stddev_pop_fieldsKeySpecifier)[];
export type user_stddev_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_stddev_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_stddev_samp_fieldsKeySpecifier)[];
export type user_stddev_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_sum_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_sum_fieldsKeySpecifier)[];
export type user_sum_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_var_pop_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_var_pop_fieldsKeySpecifier)[];
export type user_var_pop_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_var_samp_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_var_samp_fieldsKeySpecifier)[];
export type user_var_samp_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type user_variance_fieldsKeySpecifier = ('createdById' | 'id' | 'roleId' | 'updatedById' | user_variance_fieldsKeySpecifier)[];
export type user_variance_fieldsFieldPolicy = {
	createdById?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	roleId?: FieldPolicy<any> | FieldReadFunction<any>,
	updatedById?: FieldPolicy<any> | FieldReadFunction<any>
};
export type StrictTypedTypePolicies = {
	Auth0Output?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | Auth0OutputKeySpecifier | (() => undefined | Auth0OutputKeySpecifier),
		fields?: Auth0OutputFieldPolicy,
	},
	activityLogin?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLoginKeySpecifier | (() => undefined | activityLoginKeySpecifier),
		fields?: activityLoginFieldPolicy,
	},
	activityLogin_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_aggregateKeySpecifier | (() => undefined | activityLogin_aggregateKeySpecifier),
		fields?: activityLogin_aggregateFieldPolicy,
	},
	activityLogin_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_aggregate_fieldsKeySpecifier | (() => undefined | activityLogin_aggregate_fieldsKeySpecifier),
		fields?: activityLogin_aggregate_fieldsFieldPolicy,
	},
	activityLogin_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_avg_fieldsKeySpecifier | (() => undefined | activityLogin_avg_fieldsKeySpecifier),
		fields?: activityLogin_avg_fieldsFieldPolicy,
	},
	activityLogin_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_max_fieldsKeySpecifier | (() => undefined | activityLogin_max_fieldsKeySpecifier),
		fields?: activityLogin_max_fieldsFieldPolicy,
	},
	activityLogin_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_min_fieldsKeySpecifier | (() => undefined | activityLogin_min_fieldsKeySpecifier),
		fields?: activityLogin_min_fieldsFieldPolicy,
	},
	activityLogin_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_mutation_responseKeySpecifier | (() => undefined | activityLogin_mutation_responseKeySpecifier),
		fields?: activityLogin_mutation_responseFieldPolicy,
	},
	activityLogin_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_stddev_fieldsKeySpecifier | (() => undefined | activityLogin_stddev_fieldsKeySpecifier),
		fields?: activityLogin_stddev_fieldsFieldPolicy,
	},
	activityLogin_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_stddev_pop_fieldsKeySpecifier | (() => undefined | activityLogin_stddev_pop_fieldsKeySpecifier),
		fields?: activityLogin_stddev_pop_fieldsFieldPolicy,
	},
	activityLogin_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_stddev_samp_fieldsKeySpecifier | (() => undefined | activityLogin_stddev_samp_fieldsKeySpecifier),
		fields?: activityLogin_stddev_samp_fieldsFieldPolicy,
	},
	activityLogin_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_sum_fieldsKeySpecifier | (() => undefined | activityLogin_sum_fieldsKeySpecifier),
		fields?: activityLogin_sum_fieldsFieldPolicy,
	},
	activityLogin_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_var_pop_fieldsKeySpecifier | (() => undefined | activityLogin_var_pop_fieldsKeySpecifier),
		fields?: activityLogin_var_pop_fieldsFieldPolicy,
	},
	activityLogin_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_var_samp_fieldsKeySpecifier | (() => undefined | activityLogin_var_samp_fieldsKeySpecifier),
		fields?: activityLogin_var_samp_fieldsFieldPolicy,
	},
	activityLogin_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | activityLogin_variance_fieldsKeySpecifier | (() => undefined | activityLogin_variance_fieldsKeySpecifier),
		fields?: activityLogin_variance_fieldsFieldPolicy,
	},
	course?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | courseKeySpecifier | (() => undefined | courseKeySpecifier),
		fields?: courseFieldPolicy,
	},
	course_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_aggregateKeySpecifier | (() => undefined | course_aggregateKeySpecifier),
		fields?: course_aggregateFieldPolicy,
	},
	course_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_aggregate_fieldsKeySpecifier | (() => undefined | course_aggregate_fieldsKeySpecifier),
		fields?: course_aggregate_fieldsFieldPolicy,
	},
	course_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_avg_fieldsKeySpecifier | (() => undefined | course_avg_fieldsKeySpecifier),
		fields?: course_avg_fieldsFieldPolicy,
	},
	course_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_max_fieldsKeySpecifier | (() => undefined | course_max_fieldsKeySpecifier),
		fields?: course_max_fieldsFieldPolicy,
	},
	course_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_min_fieldsKeySpecifier | (() => undefined | course_min_fieldsKeySpecifier),
		fields?: course_min_fieldsFieldPolicy,
	},
	course_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_mutation_responseKeySpecifier | (() => undefined | course_mutation_responseKeySpecifier),
		fields?: course_mutation_responseFieldPolicy,
	},
	course_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_stddev_fieldsKeySpecifier | (() => undefined | course_stddev_fieldsKeySpecifier),
		fields?: course_stddev_fieldsFieldPolicy,
	},
	course_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_stddev_pop_fieldsKeySpecifier | (() => undefined | course_stddev_pop_fieldsKeySpecifier),
		fields?: course_stddev_pop_fieldsFieldPolicy,
	},
	course_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_stddev_samp_fieldsKeySpecifier | (() => undefined | course_stddev_samp_fieldsKeySpecifier),
		fields?: course_stddev_samp_fieldsFieldPolicy,
	},
	course_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_sum_fieldsKeySpecifier | (() => undefined | course_sum_fieldsKeySpecifier),
		fields?: course_sum_fieldsFieldPolicy,
	},
	course_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_var_pop_fieldsKeySpecifier | (() => undefined | course_var_pop_fieldsKeySpecifier),
		fields?: course_var_pop_fieldsFieldPolicy,
	},
	course_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_var_samp_fieldsKeySpecifier | (() => undefined | course_var_samp_fieldsKeySpecifier),
		fields?: course_var_samp_fieldsFieldPolicy,
	},
	course_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | course_variance_fieldsKeySpecifier | (() => undefined | course_variance_fieldsKeySpecifier),
		fields?: course_variance_fieldsFieldPolicy,
	},
	mutation_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | mutation_rootKeySpecifier | (() => undefined | mutation_rootKeySpecifier),
		fields?: mutation_rootFieldPolicy,
	},
	page?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | pageKeySpecifier | (() => undefined | pageKeySpecifier),
		fields?: pageFieldPolicy,
	},
	page_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_aggregateKeySpecifier | (() => undefined | page_aggregateKeySpecifier),
		fields?: page_aggregateFieldPolicy,
	},
	page_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_aggregate_fieldsKeySpecifier | (() => undefined | page_aggregate_fieldsKeySpecifier),
		fields?: page_aggregate_fieldsFieldPolicy,
	},
	page_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_avg_fieldsKeySpecifier | (() => undefined | page_avg_fieldsKeySpecifier),
		fields?: page_avg_fieldsFieldPolicy,
	},
	page_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_max_fieldsKeySpecifier | (() => undefined | page_max_fieldsKeySpecifier),
		fields?: page_max_fieldsFieldPolicy,
	},
	page_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_min_fieldsKeySpecifier | (() => undefined | page_min_fieldsKeySpecifier),
		fields?: page_min_fieldsFieldPolicy,
	},
	page_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_mutation_responseKeySpecifier | (() => undefined | page_mutation_responseKeySpecifier),
		fields?: page_mutation_responseFieldPolicy,
	},
	page_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_stddev_fieldsKeySpecifier | (() => undefined | page_stddev_fieldsKeySpecifier),
		fields?: page_stddev_fieldsFieldPolicy,
	},
	page_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_stddev_pop_fieldsKeySpecifier | (() => undefined | page_stddev_pop_fieldsKeySpecifier),
		fields?: page_stddev_pop_fieldsFieldPolicy,
	},
	page_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_stddev_samp_fieldsKeySpecifier | (() => undefined | page_stddev_samp_fieldsKeySpecifier),
		fields?: page_stddev_samp_fieldsFieldPolicy,
	},
	page_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_sum_fieldsKeySpecifier | (() => undefined | page_sum_fieldsKeySpecifier),
		fields?: page_sum_fieldsFieldPolicy,
	},
	page_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_var_pop_fieldsKeySpecifier | (() => undefined | page_var_pop_fieldsKeySpecifier),
		fields?: page_var_pop_fieldsFieldPolicy,
	},
	page_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_var_samp_fieldsKeySpecifier | (() => undefined | page_var_samp_fieldsKeySpecifier),
		fields?: page_var_samp_fieldsFieldPolicy,
	},
	page_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_variance_fieldsKeySpecifier | (() => undefined | page_variance_fieldsKeySpecifier),
		fields?: page_variance_fieldsFieldPolicy,
	},
	post?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | postKeySpecifier | (() => undefined | postKeySpecifier),
		fields?: postFieldPolicy,
	},
	post_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_aggregateKeySpecifier | (() => undefined | post_aggregateKeySpecifier),
		fields?: post_aggregateFieldPolicy,
	},
	post_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_aggregate_fieldsKeySpecifier | (() => undefined | post_aggregate_fieldsKeySpecifier),
		fields?: post_aggregate_fieldsFieldPolicy,
	},
	post_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_avg_fieldsKeySpecifier | (() => undefined | post_avg_fieldsKeySpecifier),
		fields?: post_avg_fieldsFieldPolicy,
	},
	post_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_max_fieldsKeySpecifier | (() => undefined | post_max_fieldsKeySpecifier),
		fields?: post_max_fieldsFieldPolicy,
	},
	post_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_min_fieldsKeySpecifier | (() => undefined | post_min_fieldsKeySpecifier),
		fields?: post_min_fieldsFieldPolicy,
	},
	post_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_mutation_responseKeySpecifier | (() => undefined | post_mutation_responseKeySpecifier),
		fields?: post_mutation_responseFieldPolicy,
	},
	post_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_stddev_fieldsKeySpecifier | (() => undefined | post_stddev_fieldsKeySpecifier),
		fields?: post_stddev_fieldsFieldPolicy,
	},
	post_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_stddev_pop_fieldsKeySpecifier | (() => undefined | post_stddev_pop_fieldsKeySpecifier),
		fields?: post_stddev_pop_fieldsFieldPolicy,
	},
	post_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_stddev_samp_fieldsKeySpecifier | (() => undefined | post_stddev_samp_fieldsKeySpecifier),
		fields?: post_stddev_samp_fieldsFieldPolicy,
	},
	post_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_sum_fieldsKeySpecifier | (() => undefined | post_sum_fieldsKeySpecifier),
		fields?: post_sum_fieldsFieldPolicy,
	},
	post_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_var_pop_fieldsKeySpecifier | (() => undefined | post_var_pop_fieldsKeySpecifier),
		fields?: post_var_pop_fieldsFieldPolicy,
	},
	post_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_var_samp_fieldsKeySpecifier | (() => undefined | post_var_samp_fieldsKeySpecifier),
		fields?: post_var_samp_fieldsFieldPolicy,
	},
	post_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | post_variance_fieldsKeySpecifier | (() => undefined | post_variance_fieldsKeySpecifier),
		fields?: post_variance_fieldsFieldPolicy,
	},
	profile?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profileKeySpecifier | (() => undefined | profileKeySpecifier),
		fields?: profileFieldPolicy,
	},
	profile_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_aggregateKeySpecifier | (() => undefined | profile_aggregateKeySpecifier),
		fields?: profile_aggregateFieldPolicy,
	},
	profile_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_aggregate_fieldsKeySpecifier | (() => undefined | profile_aggregate_fieldsKeySpecifier),
		fields?: profile_aggregate_fieldsFieldPolicy,
	},
	profile_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_avg_fieldsKeySpecifier | (() => undefined | profile_avg_fieldsKeySpecifier),
		fields?: profile_avg_fieldsFieldPolicy,
	},
	profile_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_max_fieldsKeySpecifier | (() => undefined | profile_max_fieldsKeySpecifier),
		fields?: profile_max_fieldsFieldPolicy,
	},
	profile_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_min_fieldsKeySpecifier | (() => undefined | profile_min_fieldsKeySpecifier),
		fields?: profile_min_fieldsFieldPolicy,
	},
	profile_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_mutation_responseKeySpecifier | (() => undefined | profile_mutation_responseKeySpecifier),
		fields?: profile_mutation_responseFieldPolicy,
	},
	profile_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_stddev_fieldsKeySpecifier | (() => undefined | profile_stddev_fieldsKeySpecifier),
		fields?: profile_stddev_fieldsFieldPolicy,
	},
	profile_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_stddev_pop_fieldsKeySpecifier | (() => undefined | profile_stddev_pop_fieldsKeySpecifier),
		fields?: profile_stddev_pop_fieldsFieldPolicy,
	},
	profile_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_stddev_samp_fieldsKeySpecifier | (() => undefined | profile_stddev_samp_fieldsKeySpecifier),
		fields?: profile_stddev_samp_fieldsFieldPolicy,
	},
	profile_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_sum_fieldsKeySpecifier | (() => undefined | profile_sum_fieldsKeySpecifier),
		fields?: profile_sum_fieldsFieldPolicy,
	},
	profile_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_var_pop_fieldsKeySpecifier | (() => undefined | profile_var_pop_fieldsKeySpecifier),
		fields?: profile_var_pop_fieldsFieldPolicy,
	},
	profile_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_var_samp_fieldsKeySpecifier | (() => undefined | profile_var_samp_fieldsKeySpecifier),
		fields?: profile_var_samp_fieldsFieldPolicy,
	},
	profile_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | profile_variance_fieldsKeySpecifier | (() => undefined | profile_variance_fieldsKeySpecifier),
		fields?: profile_variance_fieldsFieldPolicy,
	},
	query_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | query_rootKeySpecifier | (() => undefined | query_rootKeySpecifier),
		fields?: query_rootFieldPolicy,
	},
	role?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | roleKeySpecifier | (() => undefined | roleKeySpecifier),
		fields?: roleFieldPolicy,
	},
	role_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_aggregateKeySpecifier | (() => undefined | role_aggregateKeySpecifier),
		fields?: role_aggregateFieldPolicy,
	},
	role_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_aggregate_fieldsKeySpecifier | (() => undefined | role_aggregate_fieldsKeySpecifier),
		fields?: role_aggregate_fieldsFieldPolicy,
	},
	role_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_avg_fieldsKeySpecifier | (() => undefined | role_avg_fieldsKeySpecifier),
		fields?: role_avg_fieldsFieldPolicy,
	},
	role_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_max_fieldsKeySpecifier | (() => undefined | role_max_fieldsKeySpecifier),
		fields?: role_max_fieldsFieldPolicy,
	},
	role_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_min_fieldsKeySpecifier | (() => undefined | role_min_fieldsKeySpecifier),
		fields?: role_min_fieldsFieldPolicy,
	},
	role_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_mutation_responseKeySpecifier | (() => undefined | role_mutation_responseKeySpecifier),
		fields?: role_mutation_responseFieldPolicy,
	},
	role_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_stddev_fieldsKeySpecifier | (() => undefined | role_stddev_fieldsKeySpecifier),
		fields?: role_stddev_fieldsFieldPolicy,
	},
	role_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_stddev_pop_fieldsKeySpecifier | (() => undefined | role_stddev_pop_fieldsKeySpecifier),
		fields?: role_stddev_pop_fieldsFieldPolicy,
	},
	role_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_stddev_samp_fieldsKeySpecifier | (() => undefined | role_stddev_samp_fieldsKeySpecifier),
		fields?: role_stddev_samp_fieldsFieldPolicy,
	},
	role_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_sum_fieldsKeySpecifier | (() => undefined | role_sum_fieldsKeySpecifier),
		fields?: role_sum_fieldsFieldPolicy,
	},
	role_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_var_pop_fieldsKeySpecifier | (() => undefined | role_var_pop_fieldsKeySpecifier),
		fields?: role_var_pop_fieldsFieldPolicy,
	},
	role_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_var_samp_fieldsKeySpecifier | (() => undefined | role_var_samp_fieldsKeySpecifier),
		fields?: role_var_samp_fieldsFieldPolicy,
	},
	role_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | role_variance_fieldsKeySpecifier | (() => undefined | role_variance_fieldsKeySpecifier),
		fields?: role_variance_fieldsFieldPolicy,
	},
	subscription_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | subscription_rootKeySpecifier | (() => undefined | subscription_rootKeySpecifier),
		fields?: subscription_rootFieldPolicy,
	},
	tag?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tagKeySpecifier | (() => undefined | tagKeySpecifier),
		fields?: tagFieldPolicy,
	},
	tag_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_aggregateKeySpecifier | (() => undefined | tag_aggregateKeySpecifier),
		fields?: tag_aggregateFieldPolicy,
	},
	tag_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_aggregate_fieldsKeySpecifier | (() => undefined | tag_aggregate_fieldsKeySpecifier),
		fields?: tag_aggregate_fieldsFieldPolicy,
	},
	tag_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_avg_fieldsKeySpecifier | (() => undefined | tag_avg_fieldsKeySpecifier),
		fields?: tag_avg_fieldsFieldPolicy,
	},
	tag_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_max_fieldsKeySpecifier | (() => undefined | tag_max_fieldsKeySpecifier),
		fields?: tag_max_fieldsFieldPolicy,
	},
	tag_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_min_fieldsKeySpecifier | (() => undefined | tag_min_fieldsKeySpecifier),
		fields?: tag_min_fieldsFieldPolicy,
	},
	tag_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_mutation_responseKeySpecifier | (() => undefined | tag_mutation_responseKeySpecifier),
		fields?: tag_mutation_responseFieldPolicy,
	},
	tag_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_stddev_fieldsKeySpecifier | (() => undefined | tag_stddev_fieldsKeySpecifier),
		fields?: tag_stddev_fieldsFieldPolicy,
	},
	tag_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_stddev_pop_fieldsKeySpecifier | (() => undefined | tag_stddev_pop_fieldsKeySpecifier),
		fields?: tag_stddev_pop_fieldsFieldPolicy,
	},
	tag_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_stddev_samp_fieldsKeySpecifier | (() => undefined | tag_stddev_samp_fieldsKeySpecifier),
		fields?: tag_stddev_samp_fieldsFieldPolicy,
	},
	tag_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_sum_fieldsKeySpecifier | (() => undefined | tag_sum_fieldsKeySpecifier),
		fields?: tag_sum_fieldsFieldPolicy,
	},
	tag_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_var_pop_fieldsKeySpecifier | (() => undefined | tag_var_pop_fieldsKeySpecifier),
		fields?: tag_var_pop_fieldsFieldPolicy,
	},
	tag_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_var_samp_fieldsKeySpecifier | (() => undefined | tag_var_samp_fieldsKeySpecifier),
		fields?: tag_var_samp_fieldsFieldPolicy,
	},
	tag_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | tag_variance_fieldsKeySpecifier | (() => undefined | tag_variance_fieldsKeySpecifier),
		fields?: tag_variance_fieldsFieldPolicy,
	},
	topic?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topicKeySpecifier | (() => undefined | topicKeySpecifier),
		fields?: topicFieldPolicy,
	},
	topic_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_aggregateKeySpecifier | (() => undefined | topic_aggregateKeySpecifier),
		fields?: topic_aggregateFieldPolicy,
	},
	topic_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_aggregate_fieldsKeySpecifier | (() => undefined | topic_aggregate_fieldsKeySpecifier),
		fields?: topic_aggregate_fieldsFieldPolicy,
	},
	topic_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_avg_fieldsKeySpecifier | (() => undefined | topic_avg_fieldsKeySpecifier),
		fields?: topic_avg_fieldsFieldPolicy,
	},
	topic_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_max_fieldsKeySpecifier | (() => undefined | topic_max_fieldsKeySpecifier),
		fields?: topic_max_fieldsFieldPolicy,
	},
	topic_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_min_fieldsKeySpecifier | (() => undefined | topic_min_fieldsKeySpecifier),
		fields?: topic_min_fieldsFieldPolicy,
	},
	topic_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_mutation_responseKeySpecifier | (() => undefined | topic_mutation_responseKeySpecifier),
		fields?: topic_mutation_responseFieldPolicy,
	},
	topic_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_stddev_fieldsKeySpecifier | (() => undefined | topic_stddev_fieldsKeySpecifier),
		fields?: topic_stddev_fieldsFieldPolicy,
	},
	topic_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_stddev_pop_fieldsKeySpecifier | (() => undefined | topic_stddev_pop_fieldsKeySpecifier),
		fields?: topic_stddev_pop_fieldsFieldPolicy,
	},
	topic_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_stddev_samp_fieldsKeySpecifier | (() => undefined | topic_stddev_samp_fieldsKeySpecifier),
		fields?: topic_stddev_samp_fieldsFieldPolicy,
	},
	topic_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_sum_fieldsKeySpecifier | (() => undefined | topic_sum_fieldsKeySpecifier),
		fields?: topic_sum_fieldsFieldPolicy,
	},
	topic_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_var_pop_fieldsKeySpecifier | (() => undefined | topic_var_pop_fieldsKeySpecifier),
		fields?: topic_var_pop_fieldsFieldPolicy,
	},
	topic_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_var_samp_fieldsKeySpecifier | (() => undefined | topic_var_samp_fieldsKeySpecifier),
		fields?: topic_var_samp_fieldsFieldPolicy,
	},
	topic_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | topic_variance_fieldsKeySpecifier | (() => undefined | topic_variance_fieldsKeySpecifier),
		fields?: topic_variance_fieldsFieldPolicy,
	},
	user?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | userKeySpecifier | (() => undefined | userKeySpecifier),
		fields?: userFieldPolicy,
	},
	user_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_aggregateKeySpecifier | (() => undefined | user_aggregateKeySpecifier),
		fields?: user_aggregateFieldPolicy,
	},
	user_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_aggregate_fieldsKeySpecifier | (() => undefined | user_aggregate_fieldsKeySpecifier),
		fields?: user_aggregate_fieldsFieldPolicy,
	},
	user_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_avg_fieldsKeySpecifier | (() => undefined | user_avg_fieldsKeySpecifier),
		fields?: user_avg_fieldsFieldPolicy,
	},
	user_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_max_fieldsKeySpecifier | (() => undefined | user_max_fieldsKeySpecifier),
		fields?: user_max_fieldsFieldPolicy,
	},
	user_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_min_fieldsKeySpecifier | (() => undefined | user_min_fieldsKeySpecifier),
		fields?: user_min_fieldsFieldPolicy,
	},
	user_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_mutation_responseKeySpecifier | (() => undefined | user_mutation_responseKeySpecifier),
		fields?: user_mutation_responseFieldPolicy,
	},
	user_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_stddev_fieldsKeySpecifier | (() => undefined | user_stddev_fieldsKeySpecifier),
		fields?: user_stddev_fieldsFieldPolicy,
	},
	user_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_stddev_pop_fieldsKeySpecifier | (() => undefined | user_stddev_pop_fieldsKeySpecifier),
		fields?: user_stddev_pop_fieldsFieldPolicy,
	},
	user_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_stddev_samp_fieldsKeySpecifier | (() => undefined | user_stddev_samp_fieldsKeySpecifier),
		fields?: user_stddev_samp_fieldsFieldPolicy,
	},
	user_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_sum_fieldsKeySpecifier | (() => undefined | user_sum_fieldsKeySpecifier),
		fields?: user_sum_fieldsFieldPolicy,
	},
	user_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_var_pop_fieldsKeySpecifier | (() => undefined | user_var_pop_fieldsKeySpecifier),
		fields?: user_var_pop_fieldsFieldPolicy,
	},
	user_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_var_samp_fieldsKeySpecifier | (() => undefined | user_var_samp_fieldsKeySpecifier),
		fields?: user_var_samp_fieldsFieldPolicy,
	},
	user_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | user_variance_fieldsKeySpecifier | (() => undefined | user_variance_fieldsKeySpecifier),
		fields?: user_variance_fieldsFieldPolicy,
	}
};
export type TypedTypePolicies = StrictTypedTypePolicies & TypePolicies;